### ISSUE TITLE
Use input from user

### ISSUE THREAD

**Issue by mbtamuli** [MuditMaurya/Others#2]
Here you are hard coding the droplet id - https://github.com/MuditMaurya/Others/blob/d89351a35587dbc6605c8d77c0f083fc5fd3efaf/DeleteDroplet.py#L4

Instead of using hard coded data, you can use get the droplet ID in multiple ways.
1. Environment variables - Which you have already used [wonderfully here](https://github.com/MuditMaurya/Others/blob/d89351a35587dbc6605c8d77c0f083fc5fd3efaf/DeleteDroplet.py#L3)
2. User input, with an optional prompt - https://docs.python.org/3.7/library/functions.html#input
3. Command line argument - https://docs.python.org/3.3/library/argparse.html#example

The third option is not as simple as the first two and you should start with option #2, user input, and then try command line arguments later.

**Comment by MuditMaurya** [comment]
Resolved this issue by making changes in DeleteDroplet as can be seen in commit [52c9de7](https://github.com/MuditMaurya/Others/commit/52c9de722084b64ade0ca15396b6bc48992de5d9#diff-96cf5ab913570bcd88b7b1dfe2549ac7)
Closing this issue.
