### ISSUE TITLE
Virtual Environments

### ISSUE THREAD

**Issue by mbtamuli** [MuditMaurya/Others#5]
You need to use Virtual Environments. I introduced you but I am not sure you have started using them properly.

https://docs.python.org/3/tutorial/venv.html This page gives a proper introduction.

Basically
1. Create a virtual environment
```
python3 -m venv tutorial-env
```
2. Install requirements, e.g.
```
pip install requests==2.6.0
```
3. Freeze requirements. You can and should commit this file to version control
```
pip freeze > requirements.txt
```
4. Next time you setup the project elsewhere or someone else does
```
pip install -r requirements.txt
```

**Comment by MuditMaurya** [comment]
As per our discussions, I think I am going to use containers for that purpose.

**Comment by MuditMaurya** [comment]
Okay. In that case I will learn virtualenv workflow.
But I don't think it should take a form of an issue here. So I am closing this issue.

**Comment by mbtamuli** [comment]
You could keep this open and close only when you are able to add `requirements.txt` file in a commit.
